ROLE = 'USMC'

MIKEISMS = {
	# Ranks
	"1STLT" : "1st Lieutenant",
	"1STSGT": "First Sergeant",
	"2NDLT" : "2nd Lieutenant",
	"BGEN"	: "Brigadier General",
	"COL"	: "Colonel",
	"CPL"	: "Corporal", 
	"CWO2"	: "Chief Warrant Officer 2",
	"CWO3"	: "Chief Warrant Officer 3",
	"CWO4"	: "Chief Warrant Officer 4",
	"CWO5"	: "Chief Warrant Officer 5",
	"E1"	: "Private",
	"E2"	: "Private First Class",
	"E3"	: "Lance Corporal",
	"E4"	: "Corporal",
	"E5"	: "Sergeant",
	"E6"	: "Staff Sergeant",
	"E7"	: "Gunnery Sergeant",
	"E8"	: "Master Sergeant or First Sergeant",
	"E9"	: "Master Gunnery Sergeant or Sergeant Major or Sergeant Major of the Marine Corps",
	"LCPL"	: "Lance Corporal",
    	"LT"	: "Lieutenant",
	"LTCOL" : "Lieutenant Colonel",
	"LTGEN"	: "Lieutenant General",
    	"LTS"	: "Lieutenants",
	"MAJGEN": "Major General",
	"MGYSGT": "Master Gunnery Sergeant",
	"MSGT"	: "Master Sergeant",
	"O1"	: "Second Lieutenant",
    	"O2" 	: "First Lieutenant",
    	"O3" 	: "Captain",
    	"O4" 	: "Major",
    	"O5" 	: "Lieutenant Colonel",
    	"O6" 	: "Colonel",
    	"O7" 	: "Brigadier General",
    	"O8" 	: "Major General",
	"O9"	: "Lieutenant General",
	"O10"	: "General",
	"PFC"	: "Private First Class",
	"PVT"	: "Private",
	"SGTMAJ": "Sergeant Major",
	"SGT"	: "Sergeant",
	"SMMC"	: "Sergeant Major of the Marine Corps",
	"SSGT"	: "Staff Sergeant",
	"W1"	: "Warrant Officer",
	"W2"	: "Chief Warrant Officer 2",
	"W3"	: "Chief Warrant Officer 3",
	"W4"	: "Chief Warrant Officer 4",
	"W5"	: "Chief Warrant Officer 5",
	"WO"	: "Warrant Officer",
	# General
	"0802"	: "https://tenor.com/view/running-away-genitals-dildo-pink-dildo-gif-14469419",
    	"29"	: "paradise",
    	"48"	: "2 days of liberty",
    	"72"	: "3 days of liberty",
    	"96"	: "4 days of liberty",
    	"777"	: "M777 howitzer fires 155 mm artillery shells",
    	"ADJ"	: "adjunct who supports provides admin support for the commander",
    	"AMTRAC": "amphibious tractor",
    	"ANGLICO" : "Air Naval Gunfire Liaison Company",
    	"AO"	: "Area of Operations during a deployment",
    	"ARTY"	: "artillery",
    	"ASP"	: "ammunition supply point",
    	"BAH"	: "basic allowance for housing",
    	"BAS"	: "battalion aid station",
    	"BC"	: "battery commander",
    	"BCD"	: "bad conduct discharge",
    	"BEQ"	: "barracks",
    	"BLT"	: "battalion landing team",
    	"BLUF"	: "bottom line up front",
    	"BN"	: "battalion",
    	"BOOT"	: "new marine",
    	"BOQ"	: "bachelor officer quarters",
    	"BZO"	: "zeroed sight",
    	"CACO"	: "casualty assistance counseling officer",
    	"CAS"	: "close air support",
    	"CASEVAC" : "casualty evacuation",
    	"CAX"	: "combined arms exercise",
    	"CBRN"	: "chemical, biological, radiological, and nuclear",
    	"CCU"	: "correctional custody unit",
    	"CHAIRBORNE" : "marine who works in an office",
    	"CHIT"	: "voucher, receipt, or letter for special treatment",
    	"CID"	: "criminal investigation division",
    	"CIF"	: "consolidated issue facility",
    	"CMA"	: "central magazine area who tracks, issues and stores the ammunition for all training",
    	"CMC"	: "Commandant of the Marine Corps",
    	"CO"	: "commanding officer",
    	"COC"	: "combat operations center",
    	"CONUS"	: "continental United States",
    	"COVER"	: "hat",
    	"CQB"	: "close quarters battle",
    	"CQC"	: "close quarters combat",
    	"CS"	: "tear gas",
    	"DASC"	: "Direct Air Support Center",
    	"DI"	: "drill instructor",
    	"DPICM"	: "dual purpose improved conventional munitions",
    	"DRMO"	: "Defense Reutilization and Marketing Office",
    	"DRMOED" : "Dispose of an item by taking it to the Defense Reutilization and Marketing Office",
    	"DUTY"	: "sentry responsible for patrol and security of an area",
    	"EAS"	: "end of active service",
    	"EGA"	: "emblem: eagle, globe, and anchor",
    	"EOD"	: "explosive ordnance disposal",
    	"EPD"	: "extra punitive duties",
    	"EPW"	: "enemy prisoner of war",
    	"FARP"	: "forward arming and refueling point",
    	"FEBA"	: "forward edge of the battle area",
    	"FPF"	: "final protective fire, i.e., fire everything before retreating",
    	"FITREP" : "fitness report detailing proficiency and conduct and fitness for command",
    	"FMC"	: "fully mission capable",
    	"FMF"	: "fleet marine force",
    	"FMTU"	: "foreign military training unit",
    	"FRAGO"	: "fragmentary order, an addendum to published operational orders",
    	"FROCK"	: "wearing the higher grade before promotion",
    	"GITMO"	: "Guantanamo Bay",
    	"GUNNY"	: "gunnery sergeant",
    	# "HE"	: "high explosive",
    	"HEDP"	: "high explosive dual purpose ammunition",
    	"HIMARS" : "high mobility artillery rocket system",
    	"HQMC"	: "Marine Corp Headquarters",
    	"HUMP"	: "carry or lift a load",
    	"IAW"	: "in accordance with",
    	"IG"	: "inspector general",
	"ISLC"	: "Infantry Squad Leaders Course",
	"JAG"	: "Judge Advocate General",
	"JRTC"	: "Joint Readiness Training Center",
	"KEVLAR" : "helmet",
	"LCPLIC" : "lance corporal in charge",
	"LZ"	: "landing zone",
	"M777"	: "M777 howitzer fires 155 mm artillery shells",
	"MAGTF"	: "Marine Air-Ground Task Force",
	"MARFORLANT" : "Marine Forces, Atlantic",
	"MARFORPAC" : "Marine Forces, Pacific",
	"MARSOC" : "Marine Forces, Special Operations Command",
	"MCCLEO" : "Marine Corps Civilian Law Enforcement Officer",
	"MCI"	: "Marine Corps Institute",
	"MCMAP"	: "Marine Corps Martial Arts Program",
	"MCT"	: "Marine Combat Training",
	"MCSF"	: "Marine Corps Security Forces for the security of naval assets",
	"MEB"	: "Marine Expeditionary Brigade",
	"MEF"	: "Marine Expeditionary Force",
	"MEPS"	: "Military Entrance Processing Station",
	"MEU"	: "Marine Expeditionary Unit",
	"MEUSOC" : "Marine Expeditionary Unit Special Operations Capable",
    	"MOS"	: "military occupational specialty",
    	"MOUT"	: "military operation in urban terrain",
    	"MQ9"	: "Reaper Drone",
    	"MSG"	: "Marine Corps Security Guard who guards embassies",
    	"MTO"	: "Motor Transport Officer",
    	"NBCD"	: "Nuclear, Biological, Chemical Defense",
    	"NCIS"	: "Naval Criminal Investigation Service",
    	"NCO"	: "non-commissioned officer: corporal or sergeant",
    	"NCOIC"	: "non-commissioned officer in charge",
    	"NJP"	: "non-judicial punishment",
    	"NLT"	: "No Later Then",
    	"NMCI"	: "Navy/Marine Corps Intranet",
    	"OCONUS" : "outside continental United States",
    	"OCS"	: "Officer Candidate School",
    	"OIC"	: "Officer In Charge",
    	"OMPF"	: "Official Military Personnel File",
    	"OORAH"	: "chant that gets you kicked out of civilian areas",
    	"OPCON"	: "operational control",
    	"OPFOR"	: "opposing force",
    	"OPSO"	: "operations officer",
    	"PCP"	: "physical conditioning program",
    	"PCS"	: "Permanent Change of Station",
    	"PCSING": "Permanent Change of Station, i.e., moving",
    	"PHROG"	: "CH-46 Sea Knight transport helicopter",
	"PICMDEEP" : "Principles of Machine Gun Employment: (1) Pairs, (2) Interlocking Fires, (3) Coordination of Fire,  (4) Coordination in the Offense, (5) Coordination in the Defense, (6) Mutual Support, (7) Defilade, (8) Enfilade, (9) Economy, (10) Protection",
	"PMCS"	: "preventative maintenance checks and services",
	"PMO"	: "Provost Marshal's Office (military police)",
    	"POG"	: "person other than grunt",
    	"PRT"	: "physical readiness test",
    	"PT"	: "physical training",
    	"PX"	: "post exchange",
    	"QRF"	: "quick reaction force",
    	"RCO"	: "rifle combat optic",
    	"RFI"	: "request for information or ready for issue",
    	"ROE"	: "Rules of Engagement",
    	"SACO"	: "Substance Abuse Control Officer",
    	"SDI"	: "senior drill instructor",
    	"SMAT"	: "supply maintenance assistance team",
    	"SMEAC"	: "Situation, Mission, Execution, Administration & Logistics, Commands & Signals",
    	"SNCO"	: "staff non-commissioned officer, E-6 or higher",
    	"SMN"	: "said named marine",
    	"SNO"	: "said named officer",
    	"SOC"	: "special operations capable",
    	"SOG"	: "sergeant of the guard",
    	"SOTG"	: "Special Operations Training Group",
    	"SRB"	: "Service Rank Book",
    	"STOL"	: "short takeoff and landing",
    	"STOVL"	: "short takeoff vertical landing",
    	"TA"	: "training area",
    	"TAD"	: "temporary assigned duty",
    	"TBS"	: "The Basic School",
    	"TERP"	: "interpreter",
    	"TIC"	: "troops in contact",
    	"UA"	: "unauthorized absence",
    	"UCMJ"	: "Uniform Code of Military Justice",
    	"UNQ"	: "unqualified",
    	"VERTREP" : "vertical replenishment",
    	"VSTOL"	: "vertical short takeoff and landing",
    	"VTOL"	: "vertical takeoff and landing",
    	"WP"	: "white phosphorus munition",
    	"XO"	: "executive officer"
}
